---
title: "Plot total tourism Europe"
author: "Lisa Pramann"
date: "12/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries and data sets from separate script 
```{r}
library(tidyverse)
library(hrbrthemes)
library(plotly)
library(viridis)
source("98_data-wrangling-scripts/glimpse_eurostat_data.R")
source("98_data-wrangling-scripts/glimpse_covid_measures_index_europe.R") 
```

Mutating data sets  
```{r}

#glimpse(eurostat_total_percent)

tourism_total_graph <- eurostat_total_percent %>% 
  pivot_longer(., cols= 2:22, names_to = "year", values_to = "tourist_stays_percent") %>% 
  filter(States == "European Union - 27 countries (from 2020)") %>% 
  mutate(Month = lubridate::ym(year)) %>% 
  arrange(Month) 
  
#glimpse(tourism_total_graph)
#glimpse(data_covid_measures)

#Join dataframes and filter Jan/Feb 2020 to only get the pandemic-time-series
tourism_total_graph_02 <- left_join( 
  tourism_total_graph, data_covid_measures) %>% 
  filter(!year == c("2020-01", "2020-02"))

```

First glimpse at data 
```{r}

#p <- 
  
tourism_total_graph_02 %>% 
  ggplot(aes(x=Month)) +
  geom_line(aes(y = tourist_stays_percent), color = "#404788FF") +
  geom_line(aes(y = Covid_Measures_Index), color="#20A387FF") +
  scale_y_continuous(limits = c(-100, 100), breaks = c(-100, -80, -60, -40, -20, 0, 20, 40, 60, 80, 100), 
                     name = "Change in Overnight Stays (in %)", 
                     sec.axis = sec_axis(~., name = "Covid-Measures (Index 0-100)", 
                                         breaks = c( 0, 20, 40, 60, 80, 100))) +
  scale_x_date(limits = as.Date(c("2020-03-01","2021-09-01")),
              date_breaks = "2 month",
              date_minor_breaks = "month", 
              date_labels = "%m-%Y") +
  xlab("The Pandemic Months (March 2020 - September 2021)") +
  ggtitle("Development of Tourist Overnight Stays in\nEurope and Covid-19 Restrictions") +
   theme_ipsum() +
  theme(
    title =element_text(size=10, face='bold'),
    axis.title.x = element_text(size=10, margin = margin(t=20)),
    axis.title.y = element_text(color = "#404788FF", size=10),
    axis.title.y.right = element_text(color = "#20A387FF", size=10)
  )

ggsave(file = "graphs/tourism_covid_measures.png", width = 9, height = 5)

```

