---
title: "creating_graph_dom_tourism"
author: "Lisa Pramann"
date: "12/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load libraries and data sets from separate script 
```{r}
library(tidyverse)
library(hrbrthemes)
library(plotly)
library(viridis)
source("98_data-wrangling-scripts/glimpse_eurostat_data.R")
```

Creating a graphshowing Europe's domestic tourism stays compared to 2019 for the summer 2020/2021.
```{r}
#First, mutate the data set accordingly 
sum_dom_long = pivot_longer(summer_domestic_perc, !States, names_to = "date", values_to = "value")



#creating the plot 
sum_dom_long %>% 
  na.omit() %>% 
  group_by(States) %>% 
  mutate("average" = mean(value)) %>% 
  filter_at(vars(contains("States")), all_vars(! . %in% c("Euro area","European Union - 27 countries (from 2020)","European Union - 28 countries (2013-2020)","Malta", 
  "United Kingdom","Liechtenstein","Norway", "Switzerland", "Cyprus"))) %>%  
ggplot(mapping = aes(x = reorder(States, -average), y = average, fill = average)) +
  geom_col(position = "identity") + #have to specify identity or dodge otherwise it will add all the same average values together per country
  scale_y_continuous(limits = c(-30, 150), breaks = c(-40, -20, 0, 20, 40, 60, 80, 100, 120, 140)) +
  scale_fill_viridis_c(option = "mako", begin = 0.3, end = 1, direction = 1)+
  labs(x = "Country", y = "Average Change for July/Auggust (in %)", title = "Domestic tourist stays in the Summer 2020/2021 as compared to 2019", caption = "Note: France, Iceland, and Ireland results are averages of incomplete data.")+
  theme_ipsum() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


ggsave(file = "graphs/tourism_summer_domestic.png", width = 9, height = 5)

```



