---
title: "Data Science Project - Summer in Europe"
author: "Renato Franco"
date: "12/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Include libraries and source scripts 
```{r}

library(tidyverse)
library(hrbrthemes)
library(viridis)
library(lubridate)
library(magick)
library(plotly)

source("98_data-wrangling-scripts/glimpse_park_data.R")
```


```{r setup, include=FALSE}

parks <- read_csv(file = "change-visitors-parks-covid.csv")
spec(parks)

names(parks) <- c('countries', 'iso', 'Days', 'parks')

eurocountries <- c("Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France",
                   "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherland",
                   "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden")



```

```{r setup, include=FALSE}

eu_parks <- parks %>%
  filter(countries %in% eurocountries)

```

```{r}

eu_parks_mean <- eu_parks %>%
  group_by(Days) %>%
  summarize(Visits = mean(parks)) 

```  

```{r}

freq_parks_visit <- eu_parks_mean %>% 
  ggplot(aes (x = Days, y = Visits)) + 
  geom_line(size = 1.5, color ="#404788FF") + 
  geom_area(fill = "#20A387FF", alpha = 0.6) +
  scale_y_continuous(limits = c(-40, 175), 
                     breaks = c(-25, 0, 25, 50, 75, 100, 125, 150), name = "Average Change of Visits (in %)") + 
  scale_x_date(limits = as.Date(c("2020-03-01", "2021-09-01")), 
               date_breaks = "3 month", date_minor_breaks = "month", 
               date_labels = "%b (%y)", name = "Month") + 
  theme_minimal() + 
    theme(axis.title.x = element_text(size = 10),
          axis.title.y = element_text(size = 10),
          axis.title.y.right = element_text(color = "#20A387FF", size = 10)) + 
  labs(title = "Frequency of Park Visits in numbers", subtitle = "Change relative to the period before the Pandemic", caption = "Source: Our World in Data")

freq_parks_visit

```



```{r}  

interact_visits <- ggplotly(freq_parks_visit)

interact_visits


ggsave(file = "", width = 9, height = 5)

```


